depth:
  offset:
  - -0.005
  - 0.0
  - -0.003
  scale:
  - 1.0
  - 1.0
  - 1.0
kinematics:
  offset:
  - 0.0
  - 0.0
  - 0.0
  scale:
  - 1.0
  - 1.07
  - 1.0
pixel:
  offset:
  - 0.0
  - -0.005
  - -0.005
  scale:
  - 1.0
  - 1.0
  - 1.0
