corners:
- - 0.06499999999999999
  - 0.08349999999999999
  - 5.551115123125783e-17
- - -0.06499999999999997
  - 0.08349999999999999
  - 0.0
- - -0.06499999999999997
  - -0.08349999999999999
  - 5.551115123125783e-17
- - 0.065
  - -0.0835
  - 0.0
- - 0.0
  - 1.734723475976807e-18
  - 5.551115123125783e-17
extristric:
- - 0.012085258215204835
  - 0.015971287344314692
  - 0.28983988235840785
- - -0.07183340724150533
  - 0.9974124235621915
  - 0.002901538879932582
- - 0.9793601928913351
  - 0.0710837165457111
  - -0.18921077617803922
- - -0.18892743099910894
  - -0.010750003062545959
  - -0.9819322090909495
plane:
- 0.028371176991851575
- -0.16261914198749172
- -0.9862809391726827
- 0.2853230142033963
white_area_pose_cam:
- - -0.07232339008165109
  - -0.9972548257464504
  - 0.009566022384589363
  - 0.012089562163348944
- - 0.9817825610616351
  - -0.06952148454390016
  - 0.17644611189709022
  - 0.015993338840628167
- - -0.17531851204010235
  - 0.022153924181249833
  - 0.984114940353732
  - 0.28999154856283726
- - 0.0
  - 0.0
  - 0.0
  - 1.0
white_area_pose_world:
- - 1.0
  - 0.0
  - 0.0
  - 0.18220910264865114
- - 0.0
  - 1.0
  - 0.0
  - -0.0035055841431507473
- - 0.0
  - 0.0
  - 1.0
  - -0.0011081786942554739
- - 0.0
  - 0.0
  - 0.0
  - 1.0
