/**:
  ros__parameters:
    color_range_list:
      black:
        max:
        - 86
        - 187
        - 196
        min:
        - 0
        - 30
        - 92
      blue:
        max:
        - 172
        - 132
        - 117
        min:
        - 66
        - 92
        - 46
      green:
        max:
        - 203
        - 113
        - 197
        min:
        - 72
        - 49
        - 128
      red:
        max:
        - 151
        - 180
        - 163
        min:
        - 54
        - 142
        - 99
      tennis:
        max:
        - 210
        - 159
        - 255
        min:
        - 31
        - 66
        - 178
      white:
        max:
        - 255
        - 155
        - 155
        min:
        - 111
        - 100
        - 100
      yellow:
        max:
        - 255
        - 177
        - 184
        min:
        - 195
        - 110
        - 146
