depth:
  offset:
  - -0.003
  - 0.0
  - 0.0
  scale:
  - 1.0
  - 1.0
  - 1.0
kinematics:
  offset:
  - 0.011000000000000003
  - 0.006
  - 0.0
  scale:
  - 1.0
  - 1.05
  - 1.0
pixel:
  offset:
  - -0.009000000000000001
  - -0.006
  - 0.0
  scale:
  - 1.0
  - 0.97
  - 1.0
