corners:
- - 0.06499999999999999
  - 0.0835
  - 0.0
- - -0.06499999999999999
  - 0.08350000000000002
  - 0.0
- - -0.06499999999999999
  - -0.0835
  - 0.0
- - 0.06499999999999999
  - -0.0835
  - -2.7755575615628914e-17
- - -3.469446951953614e-18
  - 6.071532165918825e-18
  - 0.0
extristric:
- - -0.026269474592758982
  - 0.003540329617575994
  - 0.2281169901213484
- - 0.019540236041462378
  - 0.997639636248776
  - 0.06582807426055932
- - 0.9961119555673266
  - -0.013768814920217753
  - -0.08701374438287965
- - -0.08590198572373205
  - 0.06727240088700986
  - -0.9940298149087969
plane:
- 0.06323975957921014
- -0.08237810787291848
- -0.994592670469495
- 0.22144673155985076
white_area_pose_cam:
- - 0.01871569799239774
  - -0.9938579510527829
  - -0.10860325489683871
  - -0.026262003499099747
- - 0.9976785451977177
  - 0.011529107432535754
  - 0.06647552780135732
  - 0.0035587372924183193
- - -0.06481831007107461
  - -0.10960426689628186
  - 0.9917664124932252
  - 0.2280588309230392
- - 0.0
  - 0.0
  - 0.0
  - 1.0
white_area_pose_world:
- - 1.0
  - 0.0
  - 0.0
  - 0.1893537505752474
- - 0.0
  - 1.0
  - 0.0
  - 0.03558722803199183
- - 0.0
  - 0.0
  - 1.0
  - 0.0023675768373778994
- - 0.0
  - 0.0
  - 0.0
  - 1.0
